POST 0.0.0.0:42069/login

{
     "email": "test@test.com",
     "password": "password123"
}

POST http://0.0.0.0:42069/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI1NWE4YTA0LWZkYjEtNDRkOC1iNWMxLTY3M2JjMTcyNDI2ZSIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImNvbXBhbnlfaWQiOiI4ZDEwZTVlNC05MjU1LTRhNzgtYThmZS0wNzk1MGY3ZWRkODMiLCJyb2xlIjoiYWRtaW4iLCJpc19sb2dnZWRfaW4iOnRydWUsImlzc3VlZF9hdCI6IjIwMjMtMDktMjhUMTY6NTA6MjcuNzU2Mjk5MDM5LTA1OjAwIiwiZXhwaXJlZF9hdCI6IjIwMjMtMDktMjhUMTc6NTA6MjcuNzU2Mjk5MDkxLTA1OjAwIn0.Om-RaSCkRk8UnnDj5Ngi0ZDwFkMk8loLAigRMvi21-s

{
     "email": "andres@andrescourt.com",
     "name": "Andres Court",
     "password": "password123",
     "role": "user"
}

GET http://0.0.0.0:42069/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI1NWE4YTA0LWZkYjEtNDRkOC1iNWMxLTY3M2JjMTcyNDI2ZSIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImNvbXBhbnlfaWQiOiI4ZDEwZTVlNC05MjU1LTRhNzgtYThmZS0wNzk1MGY3ZWRkODMiLCJyb2xlIjoiYWRtaW4iLCJpc19sb2dnZWRfaW4iOnRydWUsImlzc3VlZF9hdCI6IjIwMjMtMDktMjhUMjE6MjQ6MDIuNDM5NzI4MTk1LTA1OjAwIiwiZXhwaXJlZF9hdCI6IjIwMjMtMDktMjhUMjI6MjQ6MDIuNDM5NzI4MjgxLTA1OjAwIn0.yeeo6qvrSaGD-ydLxgOBgEUt0RVefQySokFhGjP540k


b55a8a04-fdb1-44d8-b5c1-673bc172426e

DELETE http://0.0.0.0:42069/api/v1/users/7c76061d-b51a-4c63-8c06-94c6eea76ef4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI1NWE4YTA0LWZkYjEtNDRkOC1iNWMxLTY3M2JjMTcyNDI2ZSIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImNvbXBhbnlfaWQiOiI4ZDEwZTVlNC05MjU1LTRhNzgtYThmZS0wNzk1MGY3ZWRkODMiLCJyb2xlIjoiYWRtaW4iLCJpc19sb2dnZWRfaW4iOnRydWUsImlzc3VlZF9hdCI6IjIwMjMtMDktMjhUMjE6MjQ6MDIuNDM5NzI4MTk1LTA1OjAwIiwiZXhwaXJlZF9hdCI6IjIwMjMtMDktMjhUMjI6MjQ6MDIuNDM5NzI4MjgxLTA1OjAwIn0.yeeo6qvrSaGD-ydLxgOBgEUt0RVefQySokFhGjP540k
