POST 0.0.0.0:42069/login

{
     "email": "test@test.com",
     "password": "password123"
}

POST http://0.0.0.0:42069/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI1NWE4YTA0LWZkYjEtNDRkOC1iNWMxLTY3M2JjMTcyNDI2ZSIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImNvbXBhbnlfaWQiOiI4ZDEwZTVlNC05MjU1LTRhNzgtYThmZS0wNzk1MGY3ZWRkODMiLCJyb2xlIjoiYWRtaW4iLCJpc19sb2dnZWRfaW4iOnRydWUsImlzc3VlZF9hdCI6IjIwMjMtMDktMjhUMTY6NTA6MjcuNzU2Mjk5MDM5LTA1OjAwIiwiZXhwaXJlZF9hdCI6IjIwMjMtMDktMjhUMTc6NTA6MjcuNzU2Mjk5MDkxLTA1OjAwIn0.Om-RaSCkRk8UnnDj5Ngi0ZDwFkMk8loLAigRMvi21-s

{
     "email": "andres@andrescourt.com",
     "name": "Andres Court",
     "password": "password123",
     "role": "user"
}

GET http://0.0.0.0:42069/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI1NWE4YTA0LWZkYjEtNDRkOC1iNWMxLTY3M2JjMTcyNDI2ZSIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImNvbXBhbnlfaWQiOiI4ZDEwZTVlNC05MjU1LTRhNzgtYThmZS0wNzk1MGY3ZWRkODMiLCJyb2xlIjoiYWRtaW4iLCJpc19sb2dnZWRfaW4iOnRydWUsImlzc3VlZF9hdCI6IjIwMjMtMDktMjhUMjA6NTA6MTQuNTE4ODk2NjE2LTA1OjAwIiwiZXhwaXJlZF9hdCI6IjIwMjMtMDktMjhUMjE6NTA6MTQuNTE4ODk2NzgtMDU6MDAifQ.QLjCEjueTtPzq1qFu33jVXDtWxBdSNQscdnRYotw1pc
